#Example of a configuration file for the Hu-Sawicki model.
USE_PPLUS_SHOES: True
USE_PPLUS: False
USE_SN: False
USE_CC: True
USE_BAO: False
USE_DESI: True
USE_AGN: False
USE_H0: False

MODEL: 'LCDM' #Choose between 'LCDM', or 'GILA'
WITNESS_NUM: 1 #Suggestion: (model_number) + (datasets_number) 
FIXED_PARAMS: _
LOG_LIKELIHOOD_INDEX: 35 #See docs/parameters_protocol.md
NUM_WALKERS: 12
MAX_SAMPLES: 20000 #Maximum number of samples
WITNESS_FREQ: 1 #Frequency in which witness is refreshed

#For now only flat priors
M_PRIOR: [-21, -18]
BAO_PARAM_PRIOR: [120, 160]
H0_PRIOR: [60, 80]
OMEGA_M_PRIOR: [0.1, 0.3]

#For the mean values if needed:
#They have to have the same length of the number of free params.
GUEST: [-19.352, 140, 70, 0.143]
BOUNDS: [[-21, -18], [130, 150], [60, 80], [0.1,0.3]]

#Directory in which output files are stored
OUTPUT_DIR: '/GILA-output/LCDM/'

#Other things that are not in use:
#DATA_PATH: './data'
