#Example of a configuration file for the Hu-Sawicki model.

USE_SN: True
USE_CC: True
USE_BAO: False
USE_AGN: False
USE_H0: True

MODEL: 'GILA' #Choose between 'LCDM', or 'GILA'
WITNESS_NUM: 24 #Suggestion: (model_number) + (datasets_number) 
FIXED_PARAMS: 1
LOG_LIKELIHOOD_INDEX: 4 #See docs/parameters_protocol.md
NUM_WALKERS: 12
MAX_SAMPLES: 15000 #Maximum number of samples
WITNESS_FREQ: 1 #Frequency in which witness is refreshed

#For now only flat priors
M_PRIOR: [-22, -18]
L_BAR_PRIOR: [0.5, 1.5]
B_PRIOR: [2, 15] #Only read if MODEL is 'HS' or 'EXP'
H0_PRIOR: [50, 80]

#For the mean values if needed:
#They have to have the same length of the number of free params.
GUEST: [-19.352, 0.9, 5, 70.87]
BOUNDS: [[-25, -18], [0.7, 1.2], [3, 10], [64, 80]]

ALL_ANALYTIC: False #Use Basilakos et al. approximation for all parameters combination.

#Directory in which output files are stored
OUTPUT_DIR: '/fR-output/'

#Other things that are not in use:
#DATA_PATH: './data'
